- name: Get DB2 ODBC Driver Download URL from S3
  amazon.aws.s3_object:
    profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: DB2/v11.5.9_linuxx64_odbc_cli.tar.gz
    region: '{{ awsRegion }}'
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Create db2
  file:
    path: "/opt/db2"
    state: directory
    mode: '0755'    

- name: Download DB2 ODBC Driver
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: "/opt/db2"
    mode: '0755'

- name: Extract DB2 ODBC Driver
  ansible.builtin.unarchive:
    src: /opt/db2/v11.5.9_linuxx64_odbc_cli.tar.gz
    dest: /opt/db2
    remote_src: yes

- name: Change Ownership of /opt/db2 Directory
  file:
    path: /opt/db2
    state: directory
    recurse: yes
    mode: '0755'

- name: Set DB2 on PATH and LD_LIBRARY_PATH
  copy:
    dest: /etc/profile.d/db2.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/db2/odbc_cli/clidriver/bin"
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/db2/odbc_cli/clidriver/lib"