- name: AWS Initial Configuration
  hosts: local
  gather_facts: no
  tasks:
  - name: Import initial.yml
    import_tasks: initial.yml
  tags: default

- name: AWS AMI Info
  hosts: local
  gather_facts: no
  tasks:
  - name: Import ami.yml
    import_tasks: ami.yml
  
# - name: SSO 2FA
#   hosts: local
#   gather_facts: no
#   tasks:
#   - name: Import sso.yml
#     import_tasks: sso.yml
#   no_log: True
#   tags: default

- name: AWS EC2 Management
  hosts: local
  vars:
    tempName: SEM-{{ 2048 | random }}
  gather_facts: no
  tasks:
    - block:
        - name: Import aws.yml
          import_tasks: aws.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Modify OS Config
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
    - block:
        - name: Import system.yml
          import_tasks: system.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Manage Users
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks: 
    - block:
        - name: Import users.yml
          import_tasks: users.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  no_log: True
  tags: default

- name: Install Software
  hosts: awsEC2
  gather_facts: yes
  become: yes
  tasks:
    - block:
        - name: Import software.yml
          import_tasks: software.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Install Oracle Instant Client
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
    - block:
        - name: Import oracle.yml
          import_tasks: oracle.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Install DB2 Client
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import db2.yml
          import_tasks: db2.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Install IBM MQ Client
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import mq.yml
          import_tasks: mq.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Create Support Files and Directories
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
    - block:
        - name: Import createFilesDir.yml
          import_tasks: createFilesDir.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: ED 7.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import ed70.yml
          import_tasks: ed70.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: ED 8.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import ed80.yml
          import_tasks: ed80.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  
- name: ED 9.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import ed90.yml
          import_tasks: ed90.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: ED 10.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import ed100.yml
          import_tasks: ed100.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: ED 11.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import ed110.yml
          import_tasks: ed110.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: Install ED
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import ed.yml
          import_tasks: ed.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: ed

- name: Setup OpenLDAP
  hosts: awsEC2
  gather_facts: yes
  become: yes
  tasks:
    - block:
        - name: Import openldap.yml
          import_tasks: openldap.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: openldap

- name: extend 10.4.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import extend1040.yml
          import_tasks: extend1040.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: extend 10.5.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import extend1050.yml
          import_tasks: extend1050.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: extend 11.0.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import extend1100.yml
          import_tasks: extend1100.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml

- name: Install extend
  hosts: awsEC2
  gather_facts: no
  tasks:
    - block:
        - name: Import extend.yml
          import_tasks: extend.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: extend

- name: Create MOTD
  hosts: awsEC2
  gather_facts: yes
  become: yes
  tasks:
    - block:
        - name: Import motd.yml
          import_tasks: motd.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Add CRON Jobs
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
    - block:
        - name: Import cron.yml
          import_tasks: cron.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Reboot EC2 Instance
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
  - name: Reboot
    reboot:
  tags: default

- name: Final tasks
  hosts: local
  gather_facts: no
  tasks: 
  - name: Import final.yml
    import_tasks: final.yml
  tags: default