- name: Download OpenLDAP for ES Script
  get_url:
    url: https://raw.githubusercontent.com/UNiXMIT/UNiXMF/main/linux/openldap/podman.sh
    dest: /tmp/openldap.sh
    mode: '0775'

- name: Create OpenLDAP for ES Container
  shell: /tmp/openldap.sh
  chdir: /tmp

- name: Auto Start OpenLDAP Container
  cron:
    name: OpenLDAP
    special_time: reboot
    job: "/usr/bin/podman start openldap"

- name: Start ESCWA
  shell: tmux new -d -s escwa ". {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/escwa"

- name: Pause for 10 seconds
  ansible.builtin.pause:
    seconds: 10

- name: Add OpenLDAP ESCWA Security Entry
  ansible.builtin.uri:
    url: http://localhost:10086/server/v1/config/esm
    method: POST
    body_format: json
    body: |
      {
        "Name": "OpenLDAP",
        "Module": "mldap_esm",
        "ConnectionPath": "localhost:389",
        "AuthorizedID": "cn=Manager,dc=secldap,dc=com",
        "Password": "{{ myPassword }}",
        "Enabled": true,
        "CacheLimit": 1024,
        "CacheTTL": 600,
        "Config": "[LDAP]\nBASE=cn=Micro Focus,dc=secldap,dc=com\nuser class=microfocus-MFDS-User\nuser container=CN=Enterprise Server Users\ngroup container=CN=Enterprise Server User Groups\nresource container=CN=Enterprise Server Resources\n\n[Operation]\nset login count=yes\nsignon attempts=3\n\n[Verify]\nMode=MF-hash\n\n[Trace]\nModify=y\nRule=y\nGroups=y\nSearch=y\nBind=n\nTrace1=verify:*:debug\nTrace2=auth:*:*:**:debug",
        "Description": "OpenLDAP ESM"
      }
    headers:
      accept: application/json
      X-Requested-With: API
      Origin: http://localhost:10086

- name: Add OpenLDAP MFDS Security Entry
  ansible.builtin.uri:
    url: http://localhost:10086/native/v1/security/127.0.0.1/86/esm
    method: POST
    body_format: json
    body: |
      {
        "CN": "OpenLDAP",
        "description": "OpenLDAP ESM",
        "mfESMModule": "mldap_esm",
        "mfESMConnectionPath": "localhost:389",
        "mfESMID": "cn=Manager,dc=secldap,dc=com",
        "mfESMPwd": "{{ myPassword }}",
        "mfESMStatus": "Enabled",
        "mfESMCacheLimit": 1024,
        "mfESMCacheTTL": 600,
        "mfConfig": "[LDAP]\nBASE=cn=Micro Focus,dc=secldap,dc=com\nuser class=microfocus-MFDS-User\nuser container=CN=Enterprise Server Users\ngroup container=CN=Enterprise Server User Groups\nresource container=CN=Enterprise Server Resources\n\n[Operation]\nset login count=yes\nsignon attempts=3\n\n[Verify]\nMode=MF-hash\n\n[Trace]\nModify=y\nRule=y\nGroups=y\nSearch=y\nBind=n\nTrace1=verify:*:debug\nTrace2=auth:*:*:**:debug"
      }
    headers:
      accept: application/json
      X-Requested-With: API
      Origin: http://localhost:10086