- name: Create /opt/oracle Directory
  file:
    path: /opt/oracle
    state: directory
    mode: '0755'

- name: Set Oracle variables
  set_fact:
    oracle:
        base_url: "https://download.oracle.com/otn_software/linux/instantclient/2326000/"
        version: "23.26.0.0.0"
        precomp_url: "https://mturner.s3.eu-west-2.amazonaws.com/Public/Oracle/InstantClient/23/"
        precomp: "instantclient-precomp-linux.x64-23.26.0.0.0.zip"
        baseDir: "instantclient_23_0"

    oracle_packages:
      - basic
      - odbc
      - sqlplus
      - sdk

- name: Download Oracle Instant Client Packages
  get_url:
    url: "{{ oracle.base_url }}instantclient-{{ item }}-linux.x64-{{ oracle.version }}.zip"
    dest: /opt/oracle
  loop: "{{ oracle_packages }}"
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client Packages
  ansible.builtin.unarchive:
    src: /opt/oracle/instantclient-{{ item }}-linux.x64-{{ oracle.version }}.zip
    dest: /opt/oracle
    remote_src: yes
  loop: "{{ oracle_packages }}"

- name: Download Oracle Instant Client Precompiler from S3
  ansible.builtin.get_url:
    url: '{{ oracle.precomp_url }}{{ oracle.precomp }}'
    dest: /opt/oracle/{{ oracle.precomp }}
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client Precompiler Package
  ansible.builtin.unarchive:
    src: /opt/oracle/{{ oracle.precomp }}
    dest: /opt/oracle
    remote_src: yes

- name: Change Ownership of /opt/oracle Directory
  file:
    path: /opt/oracle
    state: directory
    recurse: yes
    mode: '0755'

- name: Set Oracle Instant Client on PATH and LD_LIBRARY_PATH
  copy:
    dest: /etc/profile.d/oracle.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/oracle/{{ oracle.baseDir }}:/opt/oracle/{{ oracle.baseDir }}/sdk"
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/oracle/{{ oracle.baseDir }}"

- name: Add Oracle DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/unixODBC/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK Oracle"
    block: |
      [oracle]
      Description     = Oracle ODBC Connection
      Driver          = /opt/oracle/{{ oracle.baseDir }}/libsqora.so.21.1
      Database        = {{ myUsername }}
      Servername      = 127.0.0.1:1521/FREE
      UserID          = {{ myUsername }}