- name: Set Facts
  set_fact:
    productName: 

- name: Pause for 60 seconds
  ansible.builtin.pause:
    seconds: 60

- name: Update all packages
  community.general.zypper:
    name: '*'
    state: latest
    update_cache: true
  
- name: Apply all available patches
  community.general.zypper:
    name: '*'
    state: latest
    type: patch

- name: Install Base Development
  community.general.zypper:
    name: devel_basis
    type: pattern
    state: present

- name: Add a OpenSUSE Leap repo and add its gpg key
  community.general.zypper_repository:
    repo: 'http://download.opensuse.org/distribution/leap/15.5/repo/oss/'
    name: openSUSE-Leap-15.5-OSS
    auto_import_keys: true

- name: Add MSSQL ODBC Driver Repo
  community.general.zypper_repository:
    repo: 'https://packages.microsoft.com/config/sles/15/prod.repo'
    auto_import_keys: true
  
- name: Package installation
  community.general.zypper:
    name: 
      - unixODBC-devel
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - tcpdump
      - ed
      - tmux
      - jq
      - python3
      - python3-pip
      - expect
      - postgresql
      - net-tools
      - lsof
      - spax
      - java-17-openjdk
      - libaio-devel
      - libaio-devel-32bit
      - glibc-devel
      - glibc-devel-32bit
      - glibc
      - glibc-32bit
      - libcrypt1-32bit
      - libncurses5-32bit
      - libstdc++6-32bit
      - libgcc_s1-32bit
      - libz1-32bit
      - podman
      - buildah
      - openconnect
      - unzip
    state: present
    update_cache: true

- name: Install MSSQL ODBC Driver 17
  environment:
    ACCEPT_EULA: "Y"
  community.general.zypper:
    name:
      - msodbcsql17
      - mssql-tools
    state: present

- name: Set MSSQL Tools on PATH
  copy:
    dest: /etc/profile.d/mssql.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/mssql-tools/bin"

- name: Enable Podman Socket
  ansible.builtin.shell: systemctl enable --now podman.socket