- name: Set Facts
  set_fact:
    productName: 

- name: Pause for 60 seconds
  ansible.builtin.pause:
    seconds: 60

- name: Update all packages
  community.general.zypper:
    name: '*'
    state: latest
    update_cache: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed
  
- name: Apply all available patches
  community.general.zypper:
    name: '*'
    state: latest
    type: patch
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Base Development
  community.general.zypper:
    name: devel_basis
    type: pattern
    state: present
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Add a OpenSUSE Leap repo and add its gpg key
  community.general.zypper_repository:
    repo: 'http://download.opensuse.org/distribution/leap/15.5/repo/oss/'
    name: openSUSE-Leap-15.5-OSS
    auto_import_keys: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Add MSSQL ODBC Driver Repo
  community.general.zypper_repository:
    repo: 'https://packages.microsoft.com/config/sles/15/prod.repo'
    auto_import_keys: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Uninstall default Docker
  community.general.zypper:
    name: docker
    state: absent
  
- name: Package installation
  community.general.zypper:
    name: 
      - unixODBC-devel
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - tcpdump
      - ed
      - tmux
      - jq
      - python3
      - python3-pip
      - expect
      - postgresql
      - net-tools
      - lsof
      - spax
      - java-17-openjdk
      - libaio-devel
      - libaio-devel-32bit
      - glibc-devel
      - glibc-devel-32bit
      - glibc
      - glibc-32bit
      - libcrypt1-32bit
      - libncurses5-32bit
      - 'libstdc++6-32bit'
      - libgcc_s1-32bit
      - libz1-32bit
      - podman
      - buildah
      - openconnect
      - unzip
      - xauth
      - libgtk-3-0
      - gtk3-tools
      - libjasper4
      - libnotify-tools
      - net-tools-deprecated
      - pam
      - pam-32bit
    state: present
    update_cache: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install MSSQL ODBC Driver 17
  environment:
    ACCEPT_EULA: "Y"
  community.general.zypper:
    name:
      - msodbcsql17
      - mssql-tools
    state: present
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Set MSSQL Tools on PATH
  copy:
    dest: /etc/profile.d/mssql.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/mssql-tools/bin"

- name: Enable Podman Socket
  ansible.builtin.shell: systemctl enable --now podman.socket

- name: Add MSSQL DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/unixODBC/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK MSSQL"
    block: |
      [mssql]  
      Driver = ODBC Driver 17 for SQL Server  
      Server = tcp:localhost,1433
      Encrypt = yes
      TrustServerCertificate = yes

- name: Add PostgreSQL driver in odbcinst.ini
  ansible.builtin.blockinfile:
    path: /etc/unixODBC/odbcinst.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK PostgreSQL"
    block: |
      [PostgreSQL ANSI]
      Description=PostgreSQL ODBC driver (ANSI version)
      Driver=psqlodbca.so
      Setup=libodbcpsqlS.so

      [PostgreSQL Unicode]
      Description=PostgreSQL ODBC driver (Unicode version)
      Driver=psqlodbcw.so
      Setup=libodbcpsqlS.so

- name: Add PostgreSQL DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/unixODBC/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK PostgreSQL"
    block: |
      [postgres]
      Description         = PostgreSQL ODBC connection
      Driver              = PostgreSQL Unicode
      Database            = {{ myUsername }}
      Servername          = 127.0.0.1
      UserName            = {{ myUsername }}
      Password            = {{ myPassword }}
      Port                = 5432

- name: Install yq
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/
    mode: '0775'
  register: result
  retries: 5
  delay: 30
  until: result is not failed