[local]
localhost ansible_connection=local

[awsLinux]
1.2.3.4 ansible_port=22 ansible_user=support ansible_ssh_private_key_file="~/.ssh/support.pem" 

[awsWin]
1.2.3.4 ansible_port=22 ansible_user=support ansible_password=strongPassword ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore ansible_port=5986

[all:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%%h-%%p-%%r'