- name: Disable original MOTD
  ansible.builtin.shell: chmod -x /etc/update-motd.d/*
    
- name: Create new MOTD
  copy:
    dest: "/etc/motd"
    content: |
      ****************************************************************************************************

          {{ ansible_distribution }} {{ ansible_distribution_version}}

          AcuCOBOL
            Set Environment:
              . setenvacu.sh (-h for usage)
                
              startacu.sh (-h for usage)

          MFCOBOL
            Set Environment:
              . setenvmf.sh

              startmf.sh (-h for usage)

            Install Options:
              -skipsafenet -skipautopass -IacceptEULA -ESadminID={{ myUsername }} -il=/home/products/edXXpuXX

      ****************************************************************************************************