- name: Disable original MOTD
  ansible.builtin.shell: chmod -x /etc/update-motd.d/*
    
- name: Create new MOTD
  copy:
    dest: "/etc/motd"
    content: |
      ****************************************************************************************************

          {{ ansible_distribution }} {{ ansible_distribution_version}}

          AcuCOBOL
            Set Environment:
              . setenvacu.sh (-h for usage)
                
              sudo systemctl (start|stop|restart) (acurcl|atw|acuserve|acuxdbcs|boomerang)

          MFCOBOL
            Set Environment:
              . setenvmf.sh

              sudo systemctl (start|stop|restart) (escwa|mfds|fileshare)

            Install Options:
              -IacceptEULA -ESadminID={{ myUsername }} -il=/home/products/edXXpuXX

      ****************************************************************************************************