- name: Create oracle
  file:
    path: "/home/{{ myUsername }}/oracle"
    state: directory
    owner: '{{ myUsername }}'
    group: '{{ myUsername }}'
    mode: '0775'

- name: Download Oracle Instant Client Basic Package
  get_url:
    url: https://download.oracle.com/otn_software/linux/instantclient/2113000/instantclient-basic-linux.x64-21.13.0.0.0dbru.zip
    dest: /tmp
    owner: '{{ myUsername }}'
    group: '{{ myUsername }}'
    mode: '0775'

- name: Extract Oracle Instant Client Basic Package
  ansible.builtin.unarchive:
    src: /tmp/instantclient-basic-linux.x64-21.13.0.0.0dbru.zip
    dest: /home/{{ myUsername }}/oracle
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    remote_src: yes

- name: Download Oracle Instant Client ODBC Package
  get_url:
    url: https://download.oracle.com/otn_software/linux/instantclient/2113000/instantclient-odbc-linux.x64-21.13.0.0.0dbru.zip
    dest: /tmp
    mode: '0775'

- name: Extract Oracle Instant Client ODBC Package
  ansible.builtin.unarchive:
    src: /tmp/instantclient-odbc-linux.x64-21.13.0.0.0dbru.zip
    dest: /home/{{ myUsername }}/oracle
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    remote_src: yes

- name: Set Oracle Instant Client on PATH and LD_LIBRARY_PATH
  copy:
    dest: /etc/profile.d/oracle.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/home/{{ myUsername }}/oracle/instantclient_21_13"
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/{{ myUsername }}/oracle/instantclient_21_13"