- name: Create oracle
  file:
    path: /opt/oracle
    state: directory
    mode: '0755'

- name: Set Oracle Facts
  set_fact:
    oracleBaseURL: "https://download.oracle.com/otn_software/linux/instantclient/2113000/"
    oracleBase: "instantclient-basic-linux.x64-21.13.0.0.0dbru.zip"
    oracleODBC: "instantclient-odbc-linux.x64-21.13.0.0.0dbru.zip"
    oracleSQLPlus: "instantclient-sqlplus-linux.x64-21.13.0.0.0dbru.zip"
    oracleSDK: "instantclient-sdk-linux.x64-21.13.0.0.0dbru.zip"
    oraclePrecompURL: "https://mturner.s3.eu-west-2.amazonaws.com/Public/Oracle/InstantClient/21/"
    oraclePrecomp: "instantclient-precomp-linux.x64-21.13.0.0.0dbru.zip"
    baseDir: "instantclient_21_13"

- name: Download Oracle Instant Client Basic Package
  get_url:
    url: '{{ oracleBaseURL }}{{ oracleBase }}'
    dest: /opt/oracle
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client Basic Package
  ansible.builtin.unarchive:
    src: /opt/oracle/{{ oracleBase }}
    dest: /opt/oracle
    remote_src: yes

- name: Download Oracle Instant Client ODBC Package
  get_url:
    url: '{{ oracleBaseURL }}{{ oracleODBC }}'
    dest: /opt/oracle
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client ODBC Package
  ansible.builtin.unarchive:
    src: /opt/oracle/{{ oracleODBC }}
    dest: /opt/oracle
    remote_src: yes

- name: Download Oracle Instant Client SQLPlus Package
  get_url:
    url: '{{ oracleBaseURL }}{{ oracleSQLPlus }}'
    dest: /opt/oracle
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client SQLPlus Package
  ansible.builtin.unarchive:
    src: /opt/oracle/{{ oracleSQLPlus }}
    dest: /opt/oracle
    remote_src: yes

- name: Download Oracle Instant Client SDK Package
  get_url:
    url: '{{ oracleBaseURL }}{{ oracleSDK }}'
    dest: /opt/oracle
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client SDK Package
  ansible.builtin.unarchive:
    src: /opt/oracle/{{ oracleSDK }}
    dest: /opt/oracle
    remote_src: yes

# - name: Get Oracle Instant Client Precompiler Download URL from S3
#   amazon.aws.s3_object:
#     # profile: '{{ awsProfile }}'
#     bucket: mturner
#     mode: geturl
#     object: Oracle/InstantClient/21/instantclient-precomp-linux.x64-21.13.0.0.0dbru.zip
#     region: eu-west-2
#     expiry: 4000
#     sig_v4: true
#   register: s3ora
#   delegate_to: localhost
#   become: no

- name: Download Oracle Instant Client Precompiler from S3
  ansible.builtin.get_url:
    url: '{{ oraclePrecompURL }}{{ oraclePrecomp }}'
    dest: /opt/oracle/{{ oraclePrecomp }}
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Extract Oracle Instant Client Precompiler Package
  ansible.builtin.unarchive:
    src: /opt/oracle/{{ oraclePrecomp }}
    dest: /opt/oracle
    remote_src: yes

- name: Change Ownership of /opt/oracle Directory
  file:
    path: /opt/oracle
    state: directory
    recurse: yes
    mode: '0755'

- name: Set Oracle Instant Client on PATH and LD_LIBRARY_PATH
  copy:
    dest: /etc/profile.d/oracle.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/oracle/{{ baseDir }}:/opt/oracle/{{ baseDir }}/sdk"
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/oracle/{{ baseDir }}"

- name: Add Oracle DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK Oracle"
    block: |
      [oracle]
      Description     = Oracle ODBC Connection
      Driver          = /opt/oracle/{{ baseDir }}/libsqora.so.21.1
      Database        = {{ myUsername }}
      Servername      = 127.0.0.1:1521/FREE
      UserID          = {{ myUsername }}