- name: Set Facts
  set_fact:
    productName: 

- name: Add amd64 architecture
  lineinfile:
    path: /var/lib/dpkg/arch
    line: "amd64"
    create: yes

- name: Add i386 architecture
  lineinfile:
    path: /var/lib/dpkg/arch
    line: "i386"
    create: yes

- name: Update APT Cache and install dependencies
  ansible.builtin.shell: |
    apt update
    apt install software-properties-common gpg python3 python3-apt -y

- name: Download MSSQL ODBC Driver Key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
    mode: '0775'
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Download MSSQL ODBC Driver Repo
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/prod.list
    dest: /etc/apt/sources.list.d/mssql-release.list
    mode: '0775'
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install MSSQL ODBC Driver 18
  environment:
    ACCEPT_EULA: "Y"
  ansible.builtin.apt:
    name: 
      - msodbcsql18 
      - mssql-tools18
    state: present
    allow_unauthenticated: true
    update_cache: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Set MSSQL Tools on PATH
  copy:
    dest: /etc/profile.d/mssql.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/mssql-tools18/bin"

- name: Package installation
  ansible.builtin.apt:
    name:
      - build-essential
      - openjdk-21-jdk
      - unixodbc-dev
      - wget
      - curl
      - cron
      - dos2unix
      - htop
      - 'lib32stdc++6'
      - 'libstdc++6:i386'
      - libaio-dev
      - libncurses5
      - apt-file 
      - zlib1g:i386
      - libc6:i386
      - libgc1 
      - tcpdump
      - ed
      - tmux
      - openconnect
      - jq
      - python3
      - python3-pip
      - expect
      - postgresql-client
      - odbc-postgresql
      - net-tools
      - lsof
      - pax-utils
      - podman
      - buildah
      - unzip
      - libgtk-3-0
    state: present
  register: result
  retries: 5
  delay: 30
  until: result is not failed
  
- name: Update apt-file
  command: apt-file update
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Enable Podman Socket
  ansible.builtin.shell: systemctl enable --now podman.socket

- name: Add MSSQL DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK MSSQL"
    block: |
      [mssql]  
      Driver = ODBC Driver 18 for SQL Server  
      Server = tcp:localhost,1433
      Encrypt = yes
      TrustServerCertificate = yes

# - name: Add PostgreSQL driver in odbcinst.ini
#   ansible.builtin.blockinfile:
#     path: /etc/odbcinst.ini
#     marker: "# {mark} ANSIBLE MANAGED BLOCK PostgreSQL"
#     block: |
#       [PostgreSQL ANSI]
#       Description=PostgreSQL ODBC driver (ANSI version)
#       Driver=psqlodbca.so
#       Setup=libodbcpsqlS.so

#       [PostgreSQL Unicode]
#       Description=PostgreSQL ODBC driver (Unicode version)
#       Driver=psqlodbcw.so
#       Setup=libodbcpsqlS.so

- name: Add PostgreSQL DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK PostgreSQL"
    block: |
      [postgres]
      Description         = PostgreSQL ODBC connection
      Driver              = PostgreSQL Unicode
      Database            = {{ myUsername }}
      Servername          = 127.0.0.1
      UserName            = {{ myUsername }}
      Password            = {{ myPassword }}
      Port                = 5432

- name: Install yq
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/
    mode: '0775'
  register: result
  retries: 5
  delay: 30
  until: result is not failed