- name: Set Facts
  set_fact:
    productName: 

- name: Add i386 architecture
  command: dpkg --add-architecture i386

- name: Update APT Cache
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Download MSSQL ODBC Driver Key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
    mode: '0775'

- name: Download MSSQL ODBC Driver Repo
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/prod.list
    dest: /etc/apt/sources.list.d/mssql-release.list
    mode: '0775'

- name: Install MSSQL ODBC Driver 17
  environment:
    ACCEPT_EULA: "Y"
  ansible.builtin.apt:
    name: 
      - msodbcsql17 
      - mssql-tools
    state: present
    update_cache: true

- name: Set MSSQL Tools on PATH
  copy:
    dest: /etc/profile.d/mssql.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/mssql-tools/bin"

- name: Package installation
  ansible.builtin.apt:
    name:
      - build-essential
      - openjdk-21-jdk
      - unixodbc-dev
      - wget
      - curl
      - cron
      - dos2unix
      - htop
      - lib32stdc++6
      - libstdc++6:i386
      - libaio-dev
      - libncurses5
      - apt-file 
      - zlib1g:i386
      - libc6:i386
      - libgc1 
      - tcpdump
      - ed
      - tmux
      - openconnect
      - jq
      - python3
      - python3-pip
      - expect
      - postgresql-client
      - odbc-postgresql
      - p
      - net-tools
      - lsof
      - pax-utils
      - podman
      - buildah
      - unzip
      - libgtk-3-0
    state: present
  
- name: Update apt-file
  command: apt-file update

- name: Enable Podman Socket
  ansible.builtin.shell: systemctl enable --now podman.socket