#cloud-config
repo_update: true
repo_upgrade: false
system_info:
  default_user:
    name: support
runcmd:
 - curl -s https://raw.githubusercontent.com/UNiXMIT/UNiXextend/master/linux/AcuScripts/setup.sh | bash