- name: Create extend 10.5.0 directory
  file:
    path: /home/products/acu1050shx64
    state: directory
    owner: support 
    group: support
    mode: '0775'

- name: Get extend 10.5.0 Download URL from S3
  amazon.aws.s3_object:
    profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: AcuCOBOL/1050/PU1/setup_acucob1050pmk59shACU
    region: '{{ awsRegion }}'
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Download extend 10.5.0 Installer
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: /home/products/acu1050shx64/
    mode: 0775
    
- name: Install extend 10.5.0
  shell: "printf 'y\n/home/products/acu1050shx64\n' | /home/products/acu1050shx64/setup_acucob1050pmk59shACU"

- name: Activate Licenses
  shell: "printf '{{ extendCode }}\n{{ extendKey }}\n' | /home/products/acu1050shx64/bin/activator"