- name: Initiate SSO for AWS Credentials
  ansible.builtin.expect:
    command: /root/sso.sh
    responses:
      email: '{{ ssoEmail }}'
      password: '{{ ssoPassword }}'
      token: '{{ ssoToken }}'
  # no_log: true