- name: TOTP Authentication
  ansible.builtin.expect:
    command: pfsso -a -2 TOTP
    responses:
      SSO Email: '{{ ssoEmail }}'
      SSO Password: '{{ ssoPassword }}'
      TOTP Authenticator Code: '{{ ssoToken }}'