---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
  - name: Restart SSH
    service:
      name: ssh
      state: restarted
  - name: Install EPEL
    dnf:
      name:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      state: present