- name: User management
  hosts: all
  become: true
  tasks:
    - name: Add the user '{{ myUsername }}' with primary group of 'sudo'
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512', password_salt) }}"
        groups: wheel
        append: yes
    - name: Change root password
      user:
        name: admin
        update_password: always
        password: "{{ password | password_hash('sha512', password_salt) }}"