- name: User management
  hosts: all
  remote_user: root
  tasks:
    - name: Add the user 'support' with primary group of 'sudo'
      ansible.builtin.user:
        name: support
        password: Unidos30
        group: wheel
        append: yes
    - name: Change root password
      user:
        name: admin
        update_password: always
        password: Unidos30