- name: User management
  hosts: all
  vars:
    password_salt: "H8KvP35*3^uLfJ63uW#*"
  become: true
  tasks:
    - name: Add the user '{{ myUsername }}' with primary group of 'sudo'
      ansible.builtin.user:
        name: "{{ myUsername }}"
        password: "{{ myPassword | password_hash('sha512', password_salt) }}"
        groups: wheel
        append: yes
    - name: Change root password
      user:
        name: admin
        update_password: always
        password: "{{ myPassword | password_hash('sha512', password_salt) }}"