- name: User management
  hosts: all
  vars:
    pwdhash: "{{ myPassword | password_hash }}"
  become: true
  tasks:
    - name: Add the user '{{ myUsername }}' with primary group of 'sudo'
      ansible.builtin.user:
        name: "{{ myUsername }}"
        password: pwdhash
        groups: wheel
        append: yes
    - name: Change root password
      user:
        name: admin
        update_password: always
        password: pwdhash