- name: SSO 2FA
  hosts: local
  gather_facts: no
  tasks:
    import_tasks: 
        file: sso.yml
    tags: [ default, destroy ]

- name: AWS EC2 Management
  hosts: local
  gather_facts: no
  tasks:
  - name: Create AWS EC2 instance
    ec2_instance:
      tower_callback:
        windows: true
        set_password: '{{ myPassword }}'
      name: '{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
        security-group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: running
      wait: true
    register: ec2
    tags: default

  - name: Destroy AWS EC2 instance
    ec2_instance:
      name: '{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
        security-group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: absent
    tags: [ default, destroy ]
  
  - name: Wait 60 seconds for public IP and AAP Setup
    pause:
      seconds: 60
    tags: default

  - name: Add Host to awsEC2 Group 
    add_host: 
       hostname: '{{ item.public_ip_address }}'
       ansible_user: '{{ ansibleUser }}'
       ansible_password: '{{ myPassword }}'
       ansible_connection: winrm
       ansible_winrm_transport: basic
       ansible_winrm_server_cert_validation: ignore
       ansible_port: 5986
       groups: awsEC2
    loop: '{{ ec2.instances }}'
    tags: default

- name: Optimise Ansible on Windows
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: optimise.yml
    tags: default

- name: Modify OS Config
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: system.yml
    tags: default

- name: Add Users
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: users.yml
    tags: default

- name: Install Software
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: software.yml
    tags: default

- name: Install Visual Studio 2022
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: vs2022.yml
    tags: vs2022

- name: Install VSCode + Extensions
  hosts: awsEC2
  gather_facts: no
  become: yes
  become_user: '{{ myUsername }}'
  become_method: runas
  become_flags: logon_type=interactive logon_flags=with_profile
  vars:
    ansible_become_pass: '{{ myPassword }}'
  tasks:
    import_tasks: 
        file: vscode.yml
    tags: default

- name: Create Support Files and Directories
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: createFilesDir.yml
    tags: default

- name: Install EDVS2022 8.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: edvs2022_80.yml
    tags: edvs2022_80

- name: Install EDE 8.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: ede_80.yml
    tags: ede80

- name: Install ES 8.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: es_80.yml
    tags: es80

- name: License MF Products
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: licenseServer.yml
    tags: licenseMF

- name: Install extend 10.5.0
  hosts: awsEC2
  gather_facts: no
  tasks:
    import_tasks: 
        file: extend1050.yml
    tags: extend1050

- name: Reboot EC2 Instance
  hosts: awsEC2
  gather_facts: no
  tasks:
    win_reboot:
  tags: default

- name: AWS EC2 Instance Created and Setup
  hosts: local
  gather_facts: no
  tasks:
    debug:
      msg: 
      - 'AWS ID     - {{ item.instance_id }}'
      - 'Public IP  - {{ item.public_ip_address }}'
      - 'Private IP - {{ item.private_ip_address }}'
    loop: '{{ ec2.instances }}'
    tags: default