---
- hosts: local
  gather_facts: no
  tasks:
  - name: Create AWS EC2 instance
    ec2_instance:
      tower_callback:
        windows: true
        # set_password: '{{ myPassword }}'
      name: '{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
        security-group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: running
      wait: true
    register: ec2
    when: awsState == "create" or awsState == "Create" or awsState == "CREATE"

  - name: Destroy AWS EC2 instance
    ec2_instance:
      name: '{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
        security-group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: absent
    when: awsState == "destroy" or awsState == 'Destroy' or awsState == 'DESTROY'
  
  - name: Wait 3 Minutes for public IP and AAP Setup
    pause:
      minutes: 3
    when: awsState == "create" or awsState == "Create" or awsState == "CREATE"

  - name: Add Host to awsEC2 Group 
    add_host: 
       hostname: '{{ imageName }}'
       ansible_host: '{{ ec2.instances[0].public_ip_address }}'
       ansible_user: '{{ ansibleUser }}'
       ansible_connection: winrm
       ansible_winrm_server_cert_validation: ignore
       groups: awsEC2
    when: awsState == "create" or awsState == "Create" or awsState == "CREATE"

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Modify OS Config
    import_tasks: 
        file: system.yml
    when: awsState == "create" or awsState == "Create" or awsState == "CREATE"

- hosts: local
  gather_facts: no
  tasks:
  - name: AWS EC2 Instance Created and Setup
    debug:
      msg: 
      - 'AWS IMAGE  - {{ imageName }}'
      - 'Public IP  - {{ ec2.instances[0].public_ip_address }}'
      - 'Private IP - {{ ec2.instances[0].private_ip_address }}'
    when: awsState == "create" or awsState == "Create" or awsState == "CREATE"