---
- hosts: local
  gather_facts: no
  tasks:
  - name: Create AWS EC2 instance
    ec2_instance:
      tower_callback:
        windows: true
        set_password: '{{ myPassword }}'
      name: '{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
        security-group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: running
      wait: true
    register: ec2
    tags: default

  - name: Destroy AWS EC2 instance
    ec2_instance:
      name: '{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
        security-group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: absent
    tags: destroy
  
  - name: Wait 120 seconds for public IP and AAP Setup
    pause:
      seconds: 120
    tags: default

  - name: Add Host to awsEC2 Group 
    add_host: 
       hostname: '{{ item.public_ip_address }}'
       ansible_user: '{{ ansibleUser }}'
       ansible_password: '{{ myPassword }}'
       ansible_connection: winrm
       ansible_winrm_transport: basic
       ansible_winrm_server_cert_validation: ignore
       ansible_port: 5986
       groups: awsEC2
    loop: '{{ ec2.instances }}'
    tags: default

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Modify OS Config
    import_tasks: 
        file: system.yml
    tags: default

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Add Users
    import_tasks: 
        file: users.yml
    tags: default

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Install Software
    import_tasks: 
        file: software.yml
    tags: default

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Install Visual Studio 2022
    import_tasks: 
        file: vs2022.yml
    tags: vs2022

- hosts: awsEC2
  gather_facts: no
  become: yes
  become_user: '{{ myUsername }}'
  become_method: runas
  become_flags: logon_type=interactive logon_flags=with_profile
  vars:
    ansible_become_pass: '{{ myPassword }}'
  tasks:
  - name: Install VSCode + Extensions
    import_tasks: 
        file: vscode.yml
    tags: default

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Create Support Files and Directories
    import_tasks: 
        file: createFilesDir.yml
    tags: default

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Install EDVS2022 8.0
    import_tasks: 
        file: edvs2022_80.yml
    tags: edvs2022_80

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Install EDE 8.0
    import_tasks: 
        file: ede_80.yml
    tags: ede80

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Install ES 8.0
    import_tasks: 
        file: es_80.yml
    tags: es80

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Setup JCL Region
    import_tasks: 
        file: jcl.yml
    tags: jcl

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Install extend 10.5.0
    import_tasks: 
        file: extend1050.yml
    tags: extend1050

- hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Reboot EC2 Instance
    win_reboot:
  tags: default

- hosts: local
  gather_facts: no
  tasks:
  - name: AWS EC2 Instance Created and Setup
    debug:
      msg: 
      - 'AWS ID     - {{ item.instance_id }}'
      - 'Public IP  - {{ item.public_ip_address }}'
      - 'Private IP - {{ item.private_ip_address }}'
    loop: '{{ ec2.instances }}'
    tags: default