- name: Initiate SSO for AWS Credentials
  ansible.builtin.expect:
    command: /root/sso.sh
    responses:
      SSO Email: '{{ ssoEmail }}'
      SSO Password: '{{ ssoPassword }}'
      TOTP Authenticator Code: '{{ ssoToken }}'