- name: Get DB2 Client Installer Download URL from S3
  amazon.aws.s3_object:
    # profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: DB2/v11.5.9_linuxx64_client.tar.gz
    region: eu-west-2
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Create IBM Directory for DB2
  file:
    path: "/opt/ibm"
    state: directory
    mode: '0755'   
  become: yes 

- name: Download DB2 Client Installer
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: /opt/ibm
    mode: '0755'
  become: yes

- name: Extract DB2 Client Installer
  ansible.builtin.unarchive:
    src: /opt/ibm/v11.5.9_linuxx64_client.tar.gz
    dest: /opt/ibm
    remote_src: yes
  become: yes

- name: Create DB2 Response File
  copy:
    dest: "/opt/ibm/client/db2.linux.rsp"
    content: |
      INTERACTIVE = NONE
      LIC_AGREEMENT = ACCEPT
      PROD = CLIENT
      FILE = /home/{{ myUsername }}/sqllib
      COMP = BASE_CLIENT
      INSTALL_TYPE = CUSTOM
  become: yes

- name: Change Ownership of /opt/ibm Directory
  file:
    path: /opt/ibm
    state: directory
    recurse: yes
    mode: '0755'
  become: yes

- name: Install DB2 Client
  shell: /opt/ibm/client/db2setup -r /opt/ibm/client/db2.linux.rsp

- name: Set DB2 Environment
  copy:
    dest: /etc/profile.d/db2.sh
    content: |
      #!/bin/bash
      . /home/{{ myUsername }}/sqllib/db2profile
      export PATH=$PATH:/home/{{ myUsername }}/sqllib/lib64:/home/{{ myUsername }}/sqllib/lib64/gskit:/home/{{ myUsername }}/sqllib/lib32
  become: yes

- name: Add DB2 DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    block: |
      [db2]
      Driver = /home/{{ myUsername }}/sqllib/lib64/libdb2o.so
      Database = support
      Server = localhost
      Port = 50000
      UID = {{ myUsername }}
      PWD = {{ myPassword }}
  become: yes