- name: Get {{ installerName }} Download URL from S3
  amazon.aws.s3_object:
    profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: '{{ S3Prefix }}{{ installerName }}'
    region: '{{ awsRegion }}'
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Download {{ installerName }}
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: "/home/{{ myUsername }}/MFSupport/MFInstallers/"
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: 0775
  become: yes

- name: Add ED Tags
  amazon.aws.ec2_tag:
    aws_profile: '{{ awsProfile }}'
    region: '{{ awsRegion }}'
    resource: '{{ item }}'
    tags:
      ED: '{{ installerName }}'
    state: present
  loop: "{{ hostvars['localhost'].ec2.instance_ids }}"
  delegate_to: localhost

- name: Install {{ installerName }}
  command: "/home/{{ myUsername }}/MFSupport/MFInstallers/{{ installerName }} -IacceptEULA -ESadminID={{ myUsername }} -il={{ installPath }}"
  become: yes

- name: Add License Server
  lineinfile:
    path: /var/microfocuslicensing/bin/ces.ini
    state: present
    regexp: '^lshost'
    line: 'lshost = {{ licenseServer }}'
  become: yes

- name: Start MFDS
  command: tmux new -d -s mfds ". {{ installPath }}/bin/cobsetenv && {{ installPath }}/bin/mfds --UI-on && {{ installPath }}/bin/mfds --listen-all && {{ installPath }}/bin/mfds"
  environment: 
    COBDIR: '{{ installPath }}'
  ignore_errors: yes
  become: yes

- name: Import JCL Region
  command: '{{ installPath }}/bin/mfds -g 5 /home/{{ myUsername }}/MFSupport/MFSamples/JCL/JCL.xml'
  environment: 
    COBDIR: '{{ installPath }}'
  ignore_errors: yes
  become: yes