- name: Download ED Installer
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: "/home/{{ myUsername }}/MFSupport/MFInstallers/"
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: 0775
  become: yes

- name: Install ED
  command: "/home/{{ myUsername }}/MFSupport/MFInstallers/{{ installerName }} -IacceptEULA -ESadminID={{ myUsername }} -il={{ installPath }}"
  become: yes

- name: Add License Server
  lineinfile:
    path: /var/microfocuslicensing/bin/ces.ini
    state: present
    regexp: '^lshost'
    line: 'lshost = {{ licenseServer }}'
  become: yes

- name: Start MFDS
  command: tmux new -d -s mfds ". {{ installPath }}/bin/cobsetenv && {{ installPath }}/bin/mfds --UI-on && {{ installPath }}/bin/mfds --listen-all && {{ installPath }}/bin/mfds"
  environment: 
    COBDIR: '{{ installPath }}'
  become: yes

- name: Import JCL Region
  command: '{{ installPath }}/bin/mfds -g 5 /home/{{ myUsername }}/MFSupport/MFSamples/JCL/JCL.xml'
  environment: 
    COBDIR: '{{ installPath }}'
  become: yes