- name: Get {{ installerName }} Download URL from S3
  amazon.aws.s3_object:
    # profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: '{{ S3Prefix }}{{ installerName }}'
    region: eu-west-2
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Get SafeNet License Download URL from S3
  amazon.aws.s3_object:
    # profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: ED/Licenses/lservrc.net
    region: eu-west-2
    expiry: 4000
    sig_v4: true
  register: s3sn
  delegate_to: localhost
    
- name: Get AutoPass License Download URL from S3
  amazon.aws.s3_object:
    # profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: ED/Licenses/LicFile.txt
    region: eu-west-2
    expiry: 4000
    sig_v4: true
  register: s3ap
  delegate_to: localhost

- name: Download {{ installerName }}
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: "/home/{{ myUsername }}/MFSupport/MFInstallers/"
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Download SafeNet License
  ansible.builtin.get_url:
    url: '{{ s3sn.url }}'
    dest: /tmp
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  when: edVer | int <= 90
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Download AutoPass License
  ansible.builtin.get_url:
    url: '{{ s3ap.url }}'
    dest: /tmp
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  when: edVer | int >= 80
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Add ED Tags
  amazon.aws.ec2_tag:
    # aws_profile: '{{ awsProfile }}'
    region: "{{ hostvars['localhost']['awsRegion'] }}"
    resource: '{{ item }}'
    tags:
      Name: "{{ semaphore_vars.task_details.username|upper }}-{{ imageName }} {{ productName }}"
      ED: '{{ installerName }}'
    state: present
  loop: "{{ hostvars['localhost'].ec2.instance_ids }}"
  delegate_to: localhost
  when: "'arm' not in ansible_run_tags"

- name: Add ED Tags ARM
  amazon.aws.ec2_tag:
    # aws_profile: '{{ awsProfile }}'
    region: "{{ hostvars['localhost']['awsRegion'] }}"
    resource: '{{ item }}'
    tags:
      Name: "{{ semaphore_vars.task_details.username|upper }}-{{ imageName }}-ARM {{ productName }}"
      ED: '{{ installerName }}'
    state: present
  loop: "{{ hostvars['localhost'].ec2.instance_ids }}"
  delegate_to: localhost
  when: "'amd' not in ansible_run_tags"

- name: Install {{ installerName }}
  command: './{{ installerName }} -IacceptEULA -ESadminID={{ myUsername }} -il={{ installPath }}'
  args:
    chdir: /home/{{ myUsername }}/MFSupport/MFInstallers
  become: yes

- name: Install Safenet License File
  shell: mv /tmp/lservrc.net /var/microfocuslicensing/bin/lservrc.net
  when: edVer | int <= 90
  become: yes

- name: Install AutoPass License File
  shell: mv /tmp/LicFile.txt /opt/microfocus/licensing/autopass/clientdetails/data/LicFile.txt
  when: edVer | int >= 80 and edVer | int <= 100
  become: yes

- name: Install RocketPass License File
  shell: mv /tmp/LicFile.txt /opt/rocketsoftware/licensing/rocketpass/clientdetails/data/LicFile.txt
  when: edVer | int >= 110
  become: yes

- name: Start ESCWA and MFDS
  shell: |
    . /home/{{ myUsername }}/MFSupport/MFScripts/setenvmf.sh 1
    systemctl start escwa mfds
  become: yes

- name: Pause for 10 seconds
  ansible.builtin.pause:
    seconds: 10

- name: Set SYSAD in VSAM ESM
  shell: '. {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfsecconv reset --user SYSAD --pass SYSAD'
  become: yes
  when: edVer | int >= 100

- name: Set SYSAD in Vault
  shell: . {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfsecretsadmin write microfocus/temp/admin -overwrite '{"mfUser":"SYSAD", "mfPassword":"SYSAD"}'
  become: yes
  when: edVer | int >= 100

- name: Set SYSAD in HACloud escwacreds
  shell: . {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfsecretsadmin write microfocus/hacloud/escwacreds -overwrite '{"mfUser":"SYSAD", "mfPassword":"SYSAD"}'
  become: yes
  when: edVer | int >= 100

- name: Set SYSAD in HACloud mfdscreds
  shell: . {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfsecretsadmin write microfocus/hacloud/mfdscreds -overwrite '{"mfUser":"SYSAD", "mfPassword":"SYSAD"}'
  become: yes
  when: edVer | int >= 100

- name: Import JCL Region XML
  shell: '. {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfds64 -g 5 /home/{{ myUsername }}/MFSupport/MFSamples/JCL/JCL.xml D SYSAD SYSAD'
  when: edVer | int <= 90

- name: Import JCL Region JSON
  block:
    - name: ESCWA Login
      ansible.builtin.uri:
        url: http://localhost:10086/logon
        method: POST
        body_format: json
        body: |
          {
            "mfUser": "SYSAD",
            "mfPassword": "SYSAD"
          }
        headers:
          accept: application/json
          X-Requested-With: API
          Origin: http://localhost:10086
      register: loginResponse
    
    - name: Import JCL Region JSON
      ansible.builtin.uri:
        url: http://localhost:10086/native/v1/import/127.0.0.1/86
        method: POST
        body_format: json
        src: /home/{{ myUsername }}/MFSupport/MFSamples/JCL/JCL.json
        remote_src: true
        headers:
          accept: application/json
          X-Requested-With: API
          Cookie: "{{ loginResponse.set_cookie | default('') }}"
          Origin: http://localhost:10086
  when: edVer | int >= 100

- name: Import CICS Region XML
  shell: '. {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfds64 -g 5 /home/{{ myUsername }}/MFSupport/MFSamples/CICS/CICS.xml D SYSAD SYSAD'
  when: edVer | int <= 90

- name: Import CICS Region JSON
  block:
    - name: ESCWA Login
      ansible.builtin.uri:
        url: http://localhost:10086/logon
        method: POST
        body_format: json
        body: |
          {
            "mfUser": "SYSAD",
            "mfPassword": "SYSAD"
          }
        headers:
          accept: application/json
          X-Requested-With: API
          Origin: http://localhost:10086
      register: loginResponse
    
    - name: Read CICS.json File
      ansible.builtin.slurp:
        src: /home/{{ myUsername }}/MFSupport/MFSamples/CICS/CICS.json
      register: cics_json
    
    - name: Import CICS Region JSON
      ansible.builtin.uri:
        url: http://localhost:10086/native/v1/import/127.0.0.1/86
        method: POST
        body_format: json
        body: "{{ cics_json.content | b64decode | to_json }}"
        headers:
          accept: application/json
          X-Requested-With: API
          Cookie: "{{ loginResponse.set_cookie | default('') }}"
          Origin: http://localhost:10086
  when: edVer | int >= 100

- name: Copy DFHDRDAT
  ansible.builtin.copy:
    src: '{{ installPath }}/etc/cas/dfhdrdat'
    dest: /home/{{ myUsername }}/MFSupport/MFSamples/CICS/system/dfhdrdat
    mode: '0775'
    remote_src: yes

- name: Modify mf-server.dat
  ansible.builtin.blockinfile:
    path: '{{ installPath }}/etc/mf-server.dat'
    block: |
      [JCL/SSL/passphrases]
      certificate=""
      keyfile=""

      [Web Services and J2EE/SSL/passphrases]
      certificate=""
      keyfile=""

      [Web/SSL/passphrases]
      certificate=""
      keyfile=""

      [TN3270/SSL/passphrases]
      certificate=""
      keyfile=""

      [RFA/SSL/passphrases]
      certificate=""
      keyfile=""

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/.mf.env
    state: absent
  become: yes