- name: Get {{ installerName }} Download URL from S3
  amazon.aws.s3_object:
    profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: '{{ S3Prefix }}{{ installerName }}'
    region: '{{ awsRegion }}'
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Download {{ installerName }}
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: "/home/{{ myUsername }}/MFSupport/MFInstallers/"
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  become: yes

- name: Add ED Tags
  amazon.aws.ec2_tag:
    aws_profile: '{{ awsProfile }}'
    region: '{{ awsRegion }}'
    resource: '{{ item }}'
    tags:
      ED: '{{ installerName }}'
    state: present
  loop: "{{ hostvars['localhost'].ec2.instance_ids }}"
  delegate_to: localhost

- name: Install {{ installerName }}
  command: "/home/{{ myUsername }}/MFSupport/MFInstallers/{{ installerName }} -IacceptEULA -ESadminID={{ myUsername }} -il={{ installPath }}"
  become: yes

# - name: Add License Server
#   lineinfile:
#     path: /var/microfocuslicensing/bin/ces.ini
#     state: present
#     regexp: '^lshost'
#     line: 'lshost = {{ licenseServer }}'
#   become: yes

- name: Install Safenet License File
  get_url:
    url: '{{ SafenetFile }}'
    dest: /var/microfocuslicensing/bin/lservrc.net
    mode: '0775'
  become: yes

- name: Install AutoPass License File
  get_url:
    url: '{{ AutoPassFile }}'
    dest: /opt/microfocus/licensing/autopass/clientdetails/data/LicFile.txt
    mode: '0775'
  become: yes

- name: Start MFDS
  command: tmux new -d -s mfds ". {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfds64 --UI-on ; {{ installPath }}/bin/mfds64 --listen-all ; {{ installPath }}/bin/mfds64"
  become: yes

- name: Import JCL Region
  command: '. {{ installPath }}/bin/cobsetenv ; {{ installPath }}/bin/mfds64 -g 5 /home/{{ myUsername }}/MFSupport/MFSamples/JCL/JCL.xml'
  become: yes
  become_user: root