- name: Create extend directory
  file:
    path: '{{ installPath }}'
    state: directory
    owner: '{{ myUsername }}'
    group: '{{ myUsername }}'
    mode: '0775'
  become: yes

- name: Download extend Installer
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: '{{ installPath }}'
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: 0775
  become: yes
    
- name: Install extend
  shell: "printf 'y\n{{ installPath }}\n' | {{ installPath }}/{{ installerName }}"

- name: Activate Licenses
  shell: "printf '{{ extendCode }}\n{{ extendKey }}\n' | {{ installPath }}bin/activator"