- name: Create extend directory
  file:
    path: '{{ installPath }}'
    state: directory
    owner: '{{ myUsername }}'
    group: '{{ myUsername }}'
    mode: '0775'
  become: yes

- name: Get {{ installerName }} Download URL from S3
  amazon.aws.s3_object:
    profile: '{{ awsProfile }}'
    bucket: mturner
    mode: geturl
    object: '{{ S3Prefix }}{{ installerName }}'
    region: '{{ awsRegion }}'
    expiry: 4000
    sig_v4: true
  register: s3
  delegate_to: localhost

- name: Download {{ installerName }}
  ansible.builtin.get_url:
    url: '{{ s3.url }}'
    dest: '{{ installPath }}'
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  become: yes

- name: Add extend Tags
  amazon.aws.ec2_tag:
    aws_profile: '{{ awsProfile }}'
    region: '{{ awsRegion }}'
    resource: '{{ item }}'
    tags:
      extend: '{{ installerName }}'
    state: present
  loop: "{{ hostvars['localhost'].ec2.instance_ids }}"
  delegate_to: localhost
    
# - name: Install {{ installerName }}
#   shell: "printf 'y\n{{ installPath }}\n' | {{ installPath }}{{ installerName }} && sleep 10"

# - name: Install {{ installerName }}
#   shell: |
#     expect -c "spawn {{ installPath }}{{ installerName }}; \
#     expect -re \"y/n\"; \
#     send \"y\r\"; \
#     expect -re \"Installation directory\"; \
#     send \"{{ installPath }}\r\"; \
#     expect eof
#     exit 0"

- name: Install "{{ installerName }}"
  shell: |
    spawn {{ installPath }}{{ installerName }}
    expect "y/n"
    send "y\r"
    expect "Installation directory"
    send "{{ installPath }}\r\"
    expect eof
    exit 0
  args:
    executable: /usr/bin/expect

# - name: Activate Licenses
#   shell: "printf '{{ extendCode }}\n{{ extendKey }}\n' | {{ installPath }}bin/activator && sleep 5"

- name: Activate Licenses
  shell: |
    expect -c "spawn {{ installPath }}bin/activator; \
    expect -re \"Enter the product code\"; \
    send \"{{ extendCode }}\r\"; \
    expect -re \"Enter the product key\"; \
    send \"{{ extendKey }}\r\"; \
    expect eof
    exit 0"