- name: AWS Initial Configuration
  hosts: local
  gather_facts: no
  tasks:
  - name: Import initial.yml
    import_tasks: initial.yml
  tags: default

- name: AWS AMI Info
  hosts: local
  gather_facts: no
  tasks:
  - name: Import ami.yml
    import_tasks: ami.yml

- name: AWS EC2 Management
  hosts: local
  vars:
    tempName: SEM-{{ 2048 | random }}
  gather_facts: no
  tasks:
    - block:
        - name: Import aws.yml
          import_tasks: aws.yml
      rescue: 
        - name: Import fail.yml
          import_tasks: fail.yml
  tags: default

- name: Modify OS Config
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
  - name: Import system.yml
    import_tasks: system.yml
  tags: default

- name: Manage Users
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks: 
  - name: Import users.yml
    import_tasks: users.yml
  no_log: True
  tags: default

- name: Install Software
  hosts: awsEC2
  gather_facts: yes
  become: yes
  tasks:
  - name: Import software.yml
    import_tasks: software.yml
  tags: default

- name: Install Oracle Instant Client
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
  - name: Import oracle.yml
    import_tasks: oracle.yml
    when: "'arm' not in ansible_run_tags"
  tags: default

- name: Install DB2 Client
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import db2.yml
    import_tasks: db2.yml
    when: "'arm' not in ansible_run_tags"
  tags: default

- name: Install IBM MQ Client
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import mq.yml
    import_tasks: mq.yml
    when: "'arm' not in ansible_run_tags"
  tags: default

- name: Create Support Files and Directories
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
  - name: Import createFilesDir.yml
    import_tasks: createFilesDir.yml
  tags: default

- name: Install ED
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed.yml
    import_tasks: ed.yml
  tags: ed

- name: Setup OpenLDAP
  hosts: awsEC2
  gather_facts: yes
  become: yes
  tasks:
  - name: Import openldap.yml
    import_tasks: openldap.yml
  tags: openldap

- name: Install extend
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import extend.yml
    import_tasks: extend.yml
  tags: extend

- name: Create MOTD
  hosts: awsEC2
  gather_facts: yes
  become: yes
  tasks:
  - name: Import motd.yml
    import_tasks: motd.yml
  tags: default

- name: Add CRON Jobs
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
  - name: Import cron.yml
    import_tasks: cron.yml
  tags: default

- name: Reboot EC2 Instance
  hosts: awsEC2
  gather_facts: no
  become: yes
  tasks:
  - name: Reboot
    reboot:
  tags: default

- name: Final tasks
  hosts: local
  gather_facts: no
  tasks: 
  - name: Import final.yml
    import_tasks: final.yml
  tags: default