- name: Create openldap
  file:
    path: /openldap
    state: directory
    mode: '0775'

- name: Download and Extract schema.zip
  ansible.builtin.unarchive:
    src: https://raw.githubusercontent.com/UNiXMIT/UNiXMF/main/linux/openldap/schema.zip
    dest: /openldap
    remote_src: yes

- name: Install OpenLDAP
  package:
    name:
      - openldap-servers
      - openldap-clients
      - openssl
    state: present

- name: Configure OpenLDAP for ED
  ansible.builtin.shell: |
    cd /openldap
    SLAPPASS={{ myPassword }}
    sudo systemctl stop slapd
    sed -i '/CRC.*/d' /etc/openldap/slapd.d/cn=config/olcDatabase={0}config.ldif
    sed -i '/olcAccess:.*/c\olcAccess: {0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break' /etc/openldap/slapd.d/cn=config/olcDatabase={0}config.ldif
    sed -i '/ ,cn=auth.*/d' /etc/openldap/slapd.d/cn=config/olcDatabase={0}config.ldif
    sudo systemctl start slapd
    SECRET=$(slappasswd -s $SLAPPASS)
    sed -i "/olcRootPW:.*/c\olcRootPW: $SECRET" /openldap/schema/chrootpwd.ldif 
    ldapadd -Y EXTERNAL -H ldapi:/// -f /openldap/schema/chrootpwd.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/corba.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/duaconf.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/dyngroup.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/java.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/misc.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/openldap.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/collective.ldif > /dev/null 2>&1
    ldapadd -Y EXTERNAL -H ldapi:/// -f /openldap/schema/ppolicy.ldif > /dev/null 2>&1
    sed -i "/olcRootPW:.*/c\olcRootPW: $SECRET" /openldap/schema/backend.ldif
    ldapadd -Y EXTERNAL -H ldapi:/// -f /openldap/schema/backend.ldif > /dev/null 2>&1
    sudo systemctl stop slapd
    cp /etc/openldap/schema/* /openldap/schema/
    if [[ -f "{{ installPath }}/bin/mfds" ]]; then
        {{ installPath }}/bin/mfds -l "dc=secldap,dc=com" 2 /openldap/schema/mfds.schema > /dev/null 2>&1
    elif [[ ! -f "/openldap/schema/mfds.schema" ]]; then
        printf "mfds and /openldap/schema/mfds.schema not found.\n"
        exit 1
    fi
    mkdir /openldap/config
    rm -rf /openldap/config/*
    slaptest -f /openldap/schema/schema_convert.conf -F config
    cp config/cn=config/cn=schema/cn={12}container.ldif /etc/openldap/slapd.d/cn=config/cn=schema
    cp config/cn=config/cn=schema/cn={13}mfds.ldif /etc/openldap/slapd.d/cn=config/cn=schema
    chown -R ldap /etc/openldap/slapd.d
    chmod -R 700 /etc/openldap/slapd.d
    sudo systemctl start slapd
    systemctl enable slapd
    mkdir /openldap/log
    rm -rf /openldap/log/*
    ldapadd -v -D "cn=Manager,dc=secldap,dc=com" -w $SLAPPASS -f /openldap/schema/top.ldif -H ldapi:/// > /openldap/log/top.log
    ldapadd -v -D "cn=Manager,dc=secldap,dc=com" -w $SLAPPASS -f /openldap/schema/mf-containers.ldif -H ldapi:/// > /openldap/log/mf-containers.log
    if [[ -f "{{ installPath }}/bin/mfds" ]]; then
        {{ installPath }}/bin/mfds -e "cn=Micro Focus,dc=secldap,dc=com" "cn=Enterprise Server Users" "cn=Enterprise Server User Groups" "cn=Enterprise Server Resources" 2 "/openldap/schema/mfds-users.ldif" > /dev/null 2>&1
    elif [[ ! -f "/openldap/schema/mfds-users.ldif" ]]; then
        printf "mfds and /openldap/schema/mfds-users.ldif not found.\n"
        exit 2
    fi
    ldapadd -v -D "cn=Manager,dc=secldap,dc=com" -w $SLAPPASS -f /openldap/schema/mfds-users.ldif -H ldapi:/// -c > /openldap/log/mfds-users.log
    sed 's/DC=X/CN=Micro Focus,dc=secldap,dc=com/' {{ installPath }}/etc/es_default_ldap_openldap.ldif > /openldap/schema/es_default_ldap_openldap.ldif
    sed -i '/,Data/d' /openldap/schema/es_default_ldap_openldap.ldif
    ldapadd -v -D "cn=Manager,dc=secldap,dc=com" -w $SLAPPASS -f /openldap/schema/es_default_ldap_openldap.ldif -H ldapi:/// -c > /openldap/log/es_default_ldap_openldap.ldifes_default_ldap_openldap.ldif
    ldapsearch -H ldapi:/// -x -b "cn=subschema" -s base + > /openldap/log/schema.log

# - name: Add OpenLDAP ESCWA Security Entry
#   ansible.builtin.uri:
#     url: http://localhost:10086/server/v1/config/esm
#     method: POST
#     body_format: json
#     body: '{"Name": "ADLDS", "Module": "mldap_esm", "ConnectionPath": "localhost:389", "AuthorizedID": "CN=MFReader,CN=ADAM Users,CN=Micro Focus,CN=Program Data,DC=local", "Password": "strongPassword123", "Enabled": true, "CacheLimit": 1024, "CacheTTL": 600, "Config": "[LDAP]\nBASE=cn=Micro Focus,dc=secldap,dc=com\nuser class=microfocus-MFDS-User\nuser container=CN=Enterprise Server Users\ngroup container=CN=Enterprise Server User Groups\nresource container=CN=Enterprise Server Resources\n\n[Operation]\nset login count=yes\nsignon attempts=3\n\n[Verify]\nMode=MF-hash\n\n[Trace]\nModify=y\nRule=y\nGroups=y\nSearch=y\nBind=n\nTrace1=verify:*:debug\nTrace2=auth:*:*:**:debug", "Description": "ADLDS ESM"}'
#     headers:
#       accept: application/json
#       X-Requested-With: API
#       Origin: http://localhost:10086

# - name: Add OpenLDAP MFDS Security Entry
#   ansible.builtin.uri:
#     url: http://localhost:10086/native/v1/security/127.0.0.1/86/esm
#     method: POST
#     body_format: json
#     body: '{"CN": "ADLDS", "description": "ADLDS ESM", "mfESMModule": "mldap_esm", "mfESMConnectionPath": "localhost:389", "mfESMID": "CN=MFReader,CN=ADAM Users,CN=Micro Focus,CN=Program Data,DC=local", "mfESMPwd": "strongPassword123", "mfESMStatus": "Enabled", "mfESMCacheLimit": 1024, "mfESMCacheTTL": 600, "mfConfig": "[LDAP]\nBASE=cn=Micro Focus,dc=secldap,dc=com\nuser class=microfocus-MFDS-User\nuser container=CN=Enterprise Server Users\ngroup container=CN=Enterprise Server User Groups\nresource container=CN=Enterprise Server Resources\n\n[Operation]\nset login count=yes\nsignon attempts=3\n\n[Verify]\nMode=MF-hash\n\n[Trace]\nModify=y\nRule=y\nGroups=y\nSearch=y\nBind=n\nTrace1=verify:*:debug\nTrace2=auth:*:*:**:debug", "Description": "ADLDS ESM"}'
#     headers:
#       accept: application/json
#       X-Requested-With: API
#       Origin: http://localhost:10086