- name: Install Oracle RPM Key 
  rpm_key:
    state: present
    key: https://yum.oracle.com/RPM-GPG-KEY-oracle-ol{{ ansible_distribution_major_version }}
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client RHEL9
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2112000/el9/oracle-instantclient-basic-21.12.0.0.0-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 9
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client ODBC RHEL9
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2112000/el9/oracle-instantclient-odbc-21.12.0.0.0-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 9
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client SQLPlus RHEL9
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2112000/el9/oracle-instantclient-sqlplus-21.12.0.0.0-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 9
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client SDK RHEL9
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2112000/el9/oracle-instantclient-devel-21.12.0.0.0-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 9
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client RHEL8
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2113000/oracle-instantclient-basic-21.13.0.0.0-1.el8.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 8
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client ODBC RHEL8
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2113000/oracle-instantclient-odbc-21.13.0.0.0-1.el8.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 8
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client SQLPlus RHEL8
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2113000/oracle-instantclient-sqlplus-21.13.0.0.0-1.el8.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 8
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client SDK RHEL8
  dnf: 
    name: https://download.oracle.com/otn_software/linux/instantclient/2113000/oracle-instantclient-devel-21.13.0.0.0-1.el8.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution_major_version'] | int == 8
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Create oracle
  file:
    path: /opt/oracle
    state: directory
    mode: '0777'

# - name: Get Oracle Instant Client Precompiler RHEL9 Download URL from S3
#   amazon.aws.s3_object:
#     # profile: '{{ awsProfile }}'
#     bucket: mturner
#     mode: geturl
#     object: Oracle/InstantClient/21/oracle-instantclient-precomp-21.12.0.0.0-1.el9.x86_64.rpm
#     region: eu-west-2
#     expiry: 4000
#     sig_v4: true
#   register: s3ora
#   delegate_to: localhost
#   become: no
#   when: ansible_facts['distribution_major_version'] | int == 9

- name: Download Oracle Instant Client Precompiler RHEL9 from S3
  ansible.builtin.get_url:
    url: https://mturner.s3.eu-west-2.amazonaws.com/Public/Oracle/InstantClient/21/oracle-instantclient-precomp-21.12.0.0.0-1.el9.x86_64.rpm
    dest: /opt/oracle/oracle-instantclient-precomp.x86_64.rpm
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  when: ansible_facts['distribution_major_version'] | int == 9
  register: result
  retries: 5
  delay: 30
  until: result is not failed

# - name: Get Oracle Instant Client Precompiler RHEL8 Download URL from S3
#   amazon.aws.s3_object:
#     # profile: '{{ awsProfile }}'
#     bucket: mturner
#     mode: geturl
#     object: Oracle/InstantClient/21/oracle-instantclient-precomp-21.13.0.0.0-1.el8.x86_64.rpm
#     region: eu-west-2
#     expiry: 4000
#     sig_v4: true
#   register: s3ora
#   delegate_to: localhost
#   become: no
#   when: ansible_facts['distribution_major_version'] | int == 8

- name: Download Oracle Instant Client Precompiler RHEL8 from S3
  ansible.builtin.get_url:
    url: https://mturner.s3.eu-west-2.amazonaws.com/Public/Oracle/InstantClient/21/oracle-instantclient-precomp-21.13.0.0.0-1.el8.x86_64.rpm
    dest: /opt/oracle/oracle-instantclient-precomp.x86_64.rpm
    owner: '{{ myUsername }}' 
    group: '{{ myUsername }}'
    mode: '0775'
  when: ansible_facts['distribution_major_version'] | int == 8
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install Oracle Instant Client Precompiler
  yum: 
    name: /opt/oracle/oracle-instantclient-precomp.x86_64.rpm
    state: present
    disable_gpg_check: yes

- name: Add Oracle DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK Oracle"
    block: |
      [oracle]
      Description     = Oracle ODBC Connection
      Driver          = /usr/lib/oracle/21/client64/lib/libsqora.so.21.1
      Database        = {{ myUsername }}
      Servername      = 127.0.0.1:1521/FREE
      UserID          = {{ myUsername }}