- name: Set Facts
  set_fact:
    productName: 

- name: Install EPEL key 
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

- name: Install EPEL
  package:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present

- name: Download MSSQL ODBC Driver Repo
  get_url:
    url: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/prod.repo
    dest: /etc/yum.repos.d/mssql-release.repo
    mode: '0775'

- name: Install MSSQL ODBC Driver 17
  environment:
    ACCEPT_EULA: "Y"
  package:
    name: 
      - msodbcsql17 
      - mssql-tools
    state: present

- name: Set MSSQL Tools on PATH
  copy:
    dest: /etc/profile.d/mssql.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/mssql-tools/bin"

- name: Package installation
  package:
    name:
      - '@Development tools'
      - unixODBC-devel
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - 'libstdc++-devel.i686'
      - libaio-devel
      - glibc-devel
      - glibc-devel.i686
      - glibc
      - glibc.i686
      - tcpdump
      - ed
      - tmux
      - openconnect
      - jq
      - python3
      - python3-pip
      - expect
      - postgresql
      - postgresql-odbc
      - net-tools
      - lsof
      - xterm
      - xauth
    state: present

# - name: RHEL<=7 Package installation
#   package:
#     name: 
#       - java-11-openjdk
#       - libcanberra-gtk3
#       - webkitgtk4
#     state: present
#   when: ansible_facts['distribution_major_version'] | int <= 7

- name: RHEL<=8 Package installation
  package:
    name: spax
    state: present
  when: ansible_facts['distribution_major_version'] | int <= 8

- name: RHEL>=8 Remove Default Java
  package:
    name: 
      - java*
    state: absent
  when: ansible_facts['distribution_major_version'] | int >= 8
  
- name: RHEL>=8 Package installation
  package:
    name: 
      - java-latest-openjdk
      - libnsl
      - libnsl.i686
      - libxcrypt
      - libxcrypt.i686
      - libgcc.i686
      - ncurses-libs.i686
      - zlib.i686
      - webkit2gtk3
      - PackageKit-gtk3-module
      - systemd-libs
      - systemd-libs.i686
      - podman
      - buildah
    state: present
  when: ansible_facts['distribution_major_version'] | int >= 8

- name: RHEL>=9 Package installation
  package:
    name: 
      - libxcrypt-compat
      - libxcrypt-compat.i686
    state: present
  when: ansible_facts['distribution_major_version'] | int >= 9

- name: Enable Podman Socket
  ansible.builtin.shell: systemctl enable --now podman.socket
  when: ansible_facts['distribution_major_version'] | int >= 8

- name: Add PostgreSQL driver in odbcinst.ini
  ansible.builtin.blockinfile:
    path: /etc/odbcinst.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK PostgreSQL"
    block: |
      [PostgreSQL ANSI]
      Description=PostgreSQL ODBC driver (ANSI version)
      Driver=psqlodbca.so
      Setup=libodbcpsqlS.so

      [PostgreSQL Unicode]
      Description=PostgreSQL ODBC driver (Unicode version)
      Driver=psqlodbcw.so
      Setup=libodbcpsqlS.so

- name: Add PostgreSQL DSN in odbc.ini
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK PostgreSQL"
    block: |
      [postgres]
      Description         = PostgreSQL ODBC connection
      Driver              = /usr/lib64/psqlodbcw.so
      Database            = {{ myUsername }}
      Servername          = 127.0.0.1
      UserName            = {{ myUsername }}
      Password            = {{ myPassword }}
      Port                = 5432