- name: Set Facts
  set_fact:
    productName: 

- name: Install EPEL key 
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

- name: Install EPEL
  package:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present

- name: Install CentOS RPM Key for RHEL 8 
  rpm_key:
    state: present
    key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
  when: ansible_facts['distribution_major_version'] | int == 8

- name: Install CentOS GPG Keys RPM for RHEL 8
  dnf:
    state: present
    name: 'http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/centos-gpg-keys-8-6.el8.noarch.rpm'
  when: ansible_facts['distribution_major_version'] | int == 8

- name: Install CentOS Repo for RHEL 8
  dnf:
    name: 'http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-8-6.el8.noarch.rpm'
    state: present
  when: ansible_facts['distribution_major_version'] | int == 8

- name: Enable powertools for RHEL 8
  shell: dnf config-manager --set-enabled powertools
  when: ansible_facts['distribution_major_version'] | int == 8

- name: Download MSSQL ODBC Driver Repo
  get_url:
    url: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/prod.repo
    dest: /etc/yum.repos.d/mssql-release.repo
    mode: '0775'

- name: Install MSSQL ODBC Driver 17
  environment:
    ACCEPT_EULA: "Y"
  package:
    name: 
      - msodbcsql17 
      - mssql-tools
    state: present

- name: Set MSSQL Tools on PATH
  copy:
    dest: /etc/profile.d/mssql.sh
    content: |
      #!/bin/bash
      export PATH="$PATH:/opt/mssql-tools/bin"

- name: Package installation
  package:
    name:
      - '@Development tools'
      - unixODBC-devel
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - libstdc++.i686
      - libaio-devel
      - glibc-devel
      - glibc-devel.i686
      - glibc
      - glibc.i686
      - tcpdump
      - ed
      - tmux
      - openconnect
      - jq
      - python3
      - python3-pip
      - expect
      - postgresql-odbc
      - net-tools
      - lsof
      - xterm
      - xauth
    state: present

- name: RHEL<=7 Package installation
  package:
    name: 
      - java-11-openjdk
      - libcanberra-gtk3
      - webkitgtk4
    state: present
  when: ansible_facts['distribution_major_version'] | int <= 7

- name: RHEL<=8 Package installation
  package:
    name: spax
    state: present
  when: ansible_facts['distribution_major_version'] | int <= 8

- name: RHEL>=8 Remove Default Java
  package:
    name: 
      - java*
    state: absent
  when: ansible_facts['distribution_major_version'] | int >= 8
  
- name: RHEL>=8 Package installation
  package:
    name: 
      - java-latest-openjdk
      - libnsl
      - libnsl.i686
      - libxcrypt
      - libxcrypt.i686
      - libgcc.i686
      - ncurses-libs-6.1-9.20180224.el8.i686
      - zlib.i686
      - webkit2gtk3
      - PackageKit-gtk3-module
      - systemd-libs
      - systemd-libs.i686
    state: present
  when: ansible_facts['distribution_major_version'] | int >= 8

- name: RHEL>=9 Package installation
  package:
    name: 
      - podman
      - buildah
      - libxcrypt-compat
      - libxcrypt-compat.i686
    state: present
  when: ansible_facts['distribution_major_version'] | int >= 9

- name: Enable Podman Socket
  ansible.builtin.shell: systemctl enable --now podman.socket
  when: ansible_facts['distribution_major_version'] | int >= 9