- name: Create AWS EC2 instance
  amazon.aws.ec2_instance:
    user_data: |
      #cloud-config
      system_info:
        default_user:
          name: {{ myUsername }}
    name: '{{ tempName }}'
    image_id: '{{ amis.images[-1].image_id }}'
    key_name: '{{ keyName }}'
    network_interfaces:  
      assign_public_ip: true
    security_groups: '{{ securityGroups }}'
    region: '{{ awsRegion }}'
    availability_zone: '{{ availabilityZone }}'
    # aws_profile: '{{ awsProfile }}'
    instance_type: '{{ instanceType }}'
    count: '{{ vmNum | default(1) }}'
    volumes:
    - device_name: '{{ deviceName }}'
      ebs:
        volume_type: '{{ volumeType }}'
        volume_size: '{{ volumeSize }}'
    state: running
    wait: true
  register: ec2

- name: Add Host to awsEC2 Group 
  add_host: 
      hostname: '{{ item.public_ip_address }}'
      ansible_port: 22
      ansible_user: '{{ myUsername }}'
      ansible_ssh_private_key_file: '{{ keyLocation }}'
      groups: awsEC2
  loop: '{{ ec2.instances }}'

- name: Rename AWS EC2 instance
  amazon.aws.ec2_tag:
    # aws_profile: '{{ awsProfile }}'
    region: '{{ awsRegion }}'
    resource: '{{ item }}'
    tags:
      Name: '{{ semaphore_vars.task_details.username|upper }}-{{ imageName }}'
      Owner: '{{ semaphore_vars.task_details.username|upper }}'
    state: present
  loop: '{{ ec2.instance_ids }}'

- name: SSH Check
  ansible.builtin.wait_for:
    host: '{{ item.public_ip_address }}'
    port: 22
    timeout: 120
  loop: '{{ ec2.instances }}'

- name: Wait for 30 seconds AWS Instance
  ansible.builtin.pause:
    seconds: 30