- name: Set Facts
  set_fact:
    DBSHORT: 

- name: Install EPEL
  package:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm'
    state: present
    disable_gpg_check: yes
  register: result
  retries: 5
  delay: 30
  until: result is not failed

# - name: Download EPEL RPM
#   ansible.builtin.get_url:
#     url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
#     dest: /tmp/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
#     mode: '0755'
#   become: yes
#   register: result
#   retries: 5
#   delay: 30
#   until: result is not failed

# - name: Download EPEL RPM (Alternative method)
#   ansible.builtin.command:
#     cmd: >
#       curl -fsSL
#       -o /tmp/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
#       https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
#   register: result
#   retries: 5
#   delay: 30
#   until: result is not failed

# - name: Install EPEL
#   package:
#     name: /tmp/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
#     state: present
#     disable_gpg_check: yes
#   register: result
#   retries: 5
#   delay: 30
#   until: result is not failed

- name: Package installation
  package:
    name:
      - unixODBC
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - tcpdump
      - tmux
      - openconnect
      - podman
      - buildah
    state: present
  register: result
  retries: 5
  delay: 30
  until: result is not failed