- name: Set Facts
  set_fact:
    DBSHORT: 

- name: Update all packages to latest
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install openssl-1:3.5.5-4.el9_8 - Workaround for RHEL 9 https://github.com/ansible/ansible/issues/87251
  package:
    name: openssl-1:3.5.5-4.el9_8
    state: present
  when: ansible_facts['distribution_major_version'] | int == 9
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install EPEL
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Package installation
  package:
    name:
      - unixODBC
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - tcpdump
      - tmux
      - openconnect
      - podman
      - buildah
    state: present
  register: result
  retries: 5
  delay: 30
  until: result is not failed