- name: Set Facts
  set_fact:
    DBSHORT: 

- name: Download EPEL RPM
  ansible.builtin.get_url:
    url: 'https://mturner.s3.eu-west-2.amazonaws.com/Public/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm'
    dest: /tmp/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
    mode: '0755'
  become: yes
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Install EPEL
  package:
    name: /tmp/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  register: result
  retries: 5
  delay: 30
  until: result is not failed

- name: Package installation
  package:
    name:
      - unixODBC
      - wget
      - curl
      - cronie
      - dos2unix
      - htop
      - tcpdump
      - tmux
      - openconnect
      - podman
      - buildah
    state: present
  register: result
  retries: 5
  delay: 30
  until: result is not failed