---
- hosts: all
  become: true
  tasks:
  - name: Package installation
    dnf:
      name:
        - '@Development tools'
        - libnsl
        - podman
        - buildah
        - unixODBC
        - wget
        - curl
        - cronie
        - dos2unix
        - java-11-openjdk
        - htop
        - libstdc++.i686
        - libxcrypt.i686
        - ncurses-libs-6.1-9.20180224.el8.i686
        - libaio-devel
        - glibc.i686
        - zlib-1.2.11-18.el8_5.i686
        - tcpdump
        - ed
        - glibc-devel.i686
      state: present