#cloud-config

users:
  - default
  - name: support
    gecos: Support User
    shell: /bin/bash
    groups: [wheel]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: false
    ssh_authorized_keys: ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwShi7AsI+8IC2ElQW41e6awPO2ZBUQb651/6q71TZd"]

chpasswd:
  expire: false
  list: |
    root:strongPassword123
    support:strongPassword123

runcmd:
  - |
    if grep -q "^PasswordAuthentication" /etc/ssh/sshd_config; then
      sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
    else
      echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    fi
  - systemctl restart sshd
