- name: AWS Initial Configuration
  hosts: local
  gather_facts: no
  tasks:
  - name: Import initial.yml
    import_tasks: initial.yml
  tags: default

- name: AWS AMI Info
  hosts: local
  gather_facts: no
  tasks:
  - name: Import ami.yml
    import_tasks: ami.yml

# - name: SSO 2FA
#   hosts: local
#   gather_facts: no
#   tasks:
#   - name: Import sso.yml
#     import_tasks: sso.yml
#   no_log: True
#   tags: default

- name: AWS EC2 Management
  hosts: local
  vars:
    tempName: SEM-{{ 2048 | random }}
  gather_facts: no
  tasks:
  - name: Import aws.yml
    import_tasks: aws.yml
  tags: default

- name: Optimise Ansible on Windows
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import optimise.yml
    import_tasks: optimise.yml
  tags: default

- name: Modify OS Config
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import system.yml
    import_tasks: system.yml
  tags: default

- name: Add Users
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import users.yml
    import_tasks: users.yml
  no_log: True
  tags: default

- name: Install Software
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import software.yml
    import_tasks: software.yml
  tags: default

- name: Install Oralce Instant Client
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import oracle.yml
    import_tasks: oracle.yml
  tags: default

- name: Install DB2 ODBC Drivers
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import db2.yml
    import_tasks: db2.yml
  tags: default

# - name: Install VPN
#   hosts: awsEC2
#   gather_facts: no
#   tasks:
#   - name: Import vpn.yml
#     import_tasks: vpn.yml
#   tags: default

- name: Install Visual Studio
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import vs.yml 
    import_tasks: vs.yml

- name: Install VSCode + Extensions
  hosts: awsEC2
  gather_facts: no
  become: yes
  become_user: '{{ myUsername }}'
  become_method: runas
  become_flags: logon_type=interactive logon_flags=with_profile
  vars:
    ansible_become_pass: '{{ myPassword }}'
  tasks:
  - name: Import vscode.yml
    import_tasks: vscode.yml
  no_log: True
  tags: default

- name: Modify {{ myUsername }} User OS Config
  hosts: awsEC2
  gather_facts: no
  become: yes
  become_user: '{{ myUsername }}'
  become_method: runas
  become_flags: logon_type=interactive logon_flags=with_profile
  vars:
    ansible_become_pass: '{{ myPassword }}'
  tasks:
  - name: Import systemUser.yml
    import_tasks: systemUser.yml
  no_log: True
  tags: default

- name: Create Support Files and Directories
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import createFilesDir.yml
    import_tasks: createFilesDir.yml
  tags: default

- name: Install ED 5.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed50.yml
    import_tasks: ed50.yml

- name: Install ED 6.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed60.yml
    import_tasks: ed60.yml

- name: Install ED 7.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed70.yml
    import_tasks: ed70.yml

- name: Install ED 8.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed80.yml
    import_tasks: ed80.yml

- name: Install ED 9.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed90.yml
    import_tasks: ed90.yml

- name: Install ED 10.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed100.yml
    import_tasks: ed100.yml

- name: Setup ED
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import ed.yml
    import_tasks: ed.yml

- name: Install ES 5.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es50.yml
    import_tasks: es50.yml

- name: Install ES 6.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es60.yml
    import_tasks: es60.yml

- name: Install ES 7.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es70.yml
    import_tasks: es70.yml

- name: Install ES 8.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es80.yml
    import_tasks: es80.yml

- name: Install ES 9.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es90.yml
    import_tasks: es90.yml

- name: Install ES 10.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es100.yml
    import_tasks: es100.yml

- name: Setup ES
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import es.yml
    import_tasks: es.yml

- name: Setup ADLDS
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import adlds.yml
    import_tasks: adlds.yml
  tags: adlds

- name: extend 10.4.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import extend1040.yml
    import_tasks: extend1040.yml

- name: extend 10.5.0
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import extend1050.yml
    import_tasks: extend1050.yml

- name: Install extend
  hosts: awsEC2
  gather_facts: no
  tasks:
  - name: Import extend.yml
    import_tasks: extend.yml
  tags: extend

- name: Final tasks
  hosts: local
  gather_facts: no
  tasks: 
  - name: Import final.yml
    import_tasks: final.yml
  tags: default